apiVersion: v1
kind: Service
metadata:
  name: flags-ui
  namespace: flags-ui
  labels:
    app: flags-ui
spec:
  type: NodePort
  selector:
    app: flags-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
      protocol: TCP
